### ISSUE TITLE
PHP 7.2 works

### ISSUE THREAD

**Issue by AdamSEY** [Bit-Wasp/secp256k1-php#126]
This may sound weird, but I have compiled `secp256k1-php` with php7.0 then I've removed php7.0 and installed php7.2 , enabled the extension and it did work on php7.2 and php7.1

`$ php -v`
```
PHP 7.2.12-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Nov 12 2018 09:55:44) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.12-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```

`$ php -m`
```
[PHP Modules]
...
Reflection
secp256k1
session
shmop
SimpleXML
...

[Zend Modules]
Zend OPcache

```

compiling it with php7.2 fails 

```
/root/secp256k1-php/secp256k1/secp256k1.c: In function ‘zif_secp256k1_context_randomize’:
/root/secp256k1-php/secp256k1/secp256k1.c:566:17: warning: implicit declaration of function ‘zend_throw_exception_ex’; did you mean ‘zend_try_exception_handler’? [-Wimplicit-function-declaration]
                 zend_throw_exception_ex(spl_ce_InvalidArgumentException, 0 TSRMLS_CC,
                 ^~~~~~~~~~~~~~~~~~~~~~~
                 zend_try_exception_handler
/root/secp256k1-php/secp256k1/secp256k1.c: In function ‘zif_secp256k1_ecdh’:
/root/secp256k1-php/secp256k1/secp256k1.c:1444:14: error: too few arguments to function ‘secp256k1_ecdh’
     result = secp256k1_ecdh(ctx, resultChars, pubkey, privKey->val);
              ^~~~~~~~~~~~~~
In file included from /root/secp256k1-php/secp256k1/php_secp256k1.h:3:0,
                 from /root/secp256k1-php/secp256k1/secp256k1.c:11:
/usr/local/include/secp256k1_ecdh.h:42:48: note: declared here
```

**Comment by AdamSEY** [comment]
sorry, I've opened this before see the existing one.
